### ISSUE TITLE
Is depreciated getdRdTall function necessary?

### ISSUE THREAD

**Issue by DimmestP** [ewallace/tidyqpcr#103]
From #85 Flic's code review

> I didn't understand what's happening with last function getdRdTall(), presume getdRdTall() is deprecated, suggesting to use or instead using calculate_drdt_plate() instead? Is that correct? Not especially clear from reading the .R code though, perhaps could document this a little more? https://github.com/ewallace/tidyqpcr/blob/master/R/amp_melt_curve_functions.R#L125

**Comment by ewallace** [comment]
No, it is not necessary. It was just included in order to not break some code/analysis previously.

We just have to double-check it’s not used, i.e. package passes checks and vignettes build with `getdRdTall` deleted.
