### ISSUE TITLE
Change test coverage button pointer

### ISSUE THREAD

**Issue by DimmestP** [ewallace/tidyqpcr#110]
Currently the test coverage button that appears in the README.md file refers to DimmestP/tidyqpcr/branch/function-tests-50 not the main branch of Edward's repo. However to do this Edward will need to go on https://codecov.io/, enable access to his repo and run covr::codecov(token = <codecov_token>) locally to create the write badge. Alternatively I could get it to point to the main branch of my own repo?

**Comment by ewallace** [comment]
Closed by #92?

**Comment by ewallace** [comment]
@DimmestP could I confirm that this is either already done or obsolete?
