### ISSUE TITLE
Update version 0.5, tag, and pkgdown branch

### ISSUE THREAD

**Issue by DimmestP** [ewallace/tidyqpcr#168]
Once we have completed the latest changes from Julia's review we need to update the gh-pages branch

**Comment by DimmestP** [comment]
I have already updated the pkgdown gh-page as it was too stale do a normal pull request. I basically deleted the branch and started again.

**Comment by ewallace** [comment]
Also created release [v0.5](https://github.com/ewallace/tidyqpcr/releases/tag/v0.5)
