### ISSUE TITLE
Functions to create plates with standard designs.

### ISSUE THREAD

**Issue by ewallace** [ewallace/tidyqpcr#2]
Laying out plates with multifactorial designs is a common user problem. We need functions to make this easy. Including for primer calibration.

**Comment by ewallace** [comment]
Requesting review of these plate functions from @RoseyBayne at next qPCR experiment design!

**Comment by RoseyBayne** [comment]
It would be helpful to have examples and an explanation of how to call the functions.

**Comment by ewallace** [comment]
Fixed by plate setup vignette #20 and function documentation.
