### ISSUE TITLE
Pipeline operator not working

### ISSUE THREAD

**Issue by hgla** [ewallace/tidyqpcr#21]
After loading tidyqpcr, the pipeline operator is no longer found. If I try to load dplyr afterwards to get it back, I receive the following error:
Error in value[[3L]](cond) : Package ‘dplyr’ version 0.7.6 cannot be unloaded: Error in unloadNamespace(package) : namespace ‘dplyr’ is imported by ‘tidyqpcr’ so cannot be unloaded.

**Comment by hgla** [comment]
Now working again, not sure why.

**Comment by ewallace** [comment]
That's strange. Pipeline operator is from magrittr, not from dplyr. I'll check the package dependencies and how they are dealt with.

**Comment by ewallace** [comment]
It looks like this is a namespace problem that could be solved by changing `magrittr` from "Depends" to "Imports".

See [explainer on namespace from Hadley's book]http://r-pkgs.had.co.nz/namespace.html#namespace).

**Comment by ewallace** [comment]
@hgla does updating via #23 fix this problem?

**Comment by hgla** [comment]
yes. problem solved. thanks!
