### ISSUE TITLE
Difficulty with plate creation

### ISSUE THREAD

**Issue by hgla** [ewallace/tidyqpcr#24]
Goal was to create a 384 well plate using the label_plate_rowcol(create_blank_plate(),rowkey,colkey) function but using my own manually defined colkey.
Documentation in help for label_plate_rowcol() states there may be a problem if "WellC is a character instead of a factor or integer". 
I received the following error: Error: Can't join on 'WellC' x 'WellC' because of incompatible types (integer / factor)

Problem was solved when I manually made WellC factors. Documentation should be updated that integer WellC values cause issues.

**Comment by j-aux** [comment]
I also have the same problem

**Comment by ewallace** [comment]
I've tried to fix this with the factors package `forcats`, doing automatic coercion to factors but warning the user that it has happened. Pushed to branch [create-plates-24](https://github.com/ewallace/tidyqpcr/tree/create-plates-24).  Any chance you could check this @hgla and @j-aux?

So, install the fix with:
```
devtools::install_github("ewallace/tidyqpcr",branch="create-plates-24",build_vignettes = TRUE)
```

Then try your code that gave the error. If it works, great. If not, add here as a [reproducible example](https://www.tidyverse.org/help/) and I'll see what I can do.

**Comment by ewallace** [comment]
Still needs `create_blank_plate` fix to make sure `WellC` is a factor.
