### ISSUE TITLE
Write basic test suite

### ISSUE THREAD

**Issue by ewallace** [ewallace/tidyqpcr#50]
Tidyqpcr [needs to have a test suite to be submitted to rOpenSci](https://devguide.ropensci.org/building.html#testing). This needs to be implemented with [`testthat`](https://r-pkgs.org/tests.html).

Key unit tests are the interesting/workhorse functions that calculate:
* `calculate_normvalue`
* `calculate_deltacq_bysampleid`
* `calculate_deltadeltacq_bytargetid`
* `calculate_efficiency`
* `calculate_efficiency_bytargetid`

Maybe also the creation and labeling functions?
* `create_blank_plate`
*`label_plate_rowcol`

Later can think about the other functions for curve data:
* `debaseline`
* `calculate_dydx_1`
* `calculate_drdt_plate`

(edited to reflect updated names from #62)

**Comment by ewallace** [comment]
Creating new branch `test-suite-50` for this.

* first, we will create simple unit tests that check that output is correct format (data frames with correct  column names and number of rows).
* next, we will write some small fake data for each core function, to check that its calculations are correct.
* we will attack this one "core function" at a time, prioritisation to be discussed.
* it will be very helpful to discuss test strategy with @seaaan if he has time?

**Comment by seaaan** [comment]
Sure, happy to discuss! Let me know how I can help.
