### ISSUE TITLE
Fix vignette names

### ISSUE THREAD

**Issue by ewallace** [ewallace/tidyqpcr#61]
Package checks with devtools is giving some warnings with inconsistent vignette names in different places.

Also `browseVignettes("tidyqpcr")` is not giving any results. Despite vignettes existing.

We should:
* fix these by giving vignettes coherent names
* check that all cross-references between vignettes and help/README files are in place and accurate.

**Comment by ewallace** [comment]
This should be a quick-fix, we hope...

**Comment by DimmestP** [comment]
I am not entirely sure I understand what the issue is here? I don't see only warnings about vignette names from devtools::check() and when I run browseVignettes("tidyqpcr") all vignettes appear perfectly?

**Comment by ewallace** [comment]
Argh! Turns out that my problem is that RStudio "Install and restart" button is not rebuilding vignettes. However, 
`devtools::install(build_vignettes = TRUE)` from tidyqpcr directory does install vignettes. We already have `devtools::install_github(build_vignettes = TRUE)` in install instructions on github. So I just have to change my workflow for installation. 

Thanks for checking.
