### ISSUE TITLE
Inconsistent function nomenclature

### ISSUE THREAD

**Issue by DimmestP** [ewallace/tidyqpcr#78]
deltacq vs delta_cq

Both the calculate_deltacq_bysampleid and calculate_deltadeltacq_bytargetid functions inside the calculate_deltacq.R file create tibble columns called delta_cq and deltadelta_cq. Therefore, should there be an underscore in all function/file names or should the column names be changed? The same is true for sample_id.

Possible alternatives include:
calculate_delta_cq_bysampleid
calculate_delta_cq_bysample_id
calculate_delta_cq_by_sample_id

**Comment by ewallace** [comment]
Good call, I think we should be consistent. Mild preference for `deltacq` (no underscore). What do you think? is there any reason to abbreviate further to `dcq` and `ddcq`?

**Comment by DimmestP** [comment]
I would always try to be explicit and shy away from dcq but I am happy with removing the underscore leaving `deltacq`. What about `bysampleid` and `bytargetid` should they be `by_sample_id` and `by_target_id`?

**Comment by ewallace** [comment]
I lost track of this - let's discuss and agree a fix at next tidyqpcr meeting.
