### ISSUE TITLE
Outdated dplyr data masking

### ISSUE THREAD

**Issue by DimmestP** [ewallace/tidyqpcr#79]
Currently user provided variables for dplyr manipulation are used in the following way

` dplyr::filter(value_df, !!dplyr::sym(id_name) %in% ref_ids)`

where id_name is defined in the function call,

`function(id_name = "id")`.

The dplyr::sym way of dealing with indirection is no longer recommended, instead the double bracing is encouraged, {{var}} and .data[[var]]. For example,

` dplyr::filter(value_df, .data[[id_name]] %in% ref_ids)`

**Comment by ewallace** [comment]
Good find, do fix it. I remember adding the `dplyr::sym` in a panic of just finding *some* way to mass in the name, I'm very happy to upgrade it to best practice.

**Comment by ewallace** [comment]
Closed along with #82.
