### ISSUE TITLE
Flic code review

### ISSUE THREAD

**Issue by DimmestP** [ewallace/tidyqpcr#85]
# tidyqpcr - Code Review Notes
## 27 May 2021

Code reviewed: 

At main repo:  https://github.com/ewallace/tidyqpcr/ 
On MASTER branch: 

- main repo files (e.g readme, description, vignettes)
- plate_functions.R
- calculate_deltacq.R
- amp_melt_curve_functions

# ----------- #

MAIN REPO: 

NICE: 
 - use of tags on most issue tickets 
 - nice .Rmd vignettes. Didn't assess for content, but R code was easy to read, well presented, generate HTML fine 
 - README is great, gives good context for the current state of the package & future aims/goals/direction.
 - contributor guide is clear
 - liked the 'repostatus' badge: https://www.repostatus.org/#active 

QUESTION / MAYBE-FIX?: 
- vignettes are great, but is the rainbow colour-scheme used visual-impairment friendly?  The rainbow-confetti effect is sometimes a little hard to read for me, but has it been checked for accessibility? Could this current plotting display theme be assessed or a known accessible theme used? 
- given the README motivations, makes sense to add `howfairis` button feature: https://github.com/fair-software/howfairis-github-action  
- re: DESCRIPTION (https://github.com/ewallace/tidyqpcr/blob/master/DESCRIPTION) - given package dependencies and suggested packages, is it worth including 'tidyverse' if you're already installing/requiring MOST of the tidyverse packages? Alternatively, worth specifying 'tidyverse' as a dependency itself and dropping the included packages?  
- add some detail somewhere on what the `inst/extdata` folder (https://github.com/ewallace/tidyqpcr/tree/master/inst/extdata) is about, what it contains and when potential developers would need to get involved with this?  I don't think this is a 'typical' R package structure item, so adding a bit of information about what's in there (a README within the folder?) and how it's used might help increase the 'bus factor' of the project!

FIX: 
 - address 'ADD HERE' in vignette `platesetup_vignette.Rmd` https://github.com/ewallace/tidyqpcr/blob/master/vignettes/platesetup_vignette.Rmd#L289 

# ----------- #

R SCRIPT: plate_functions.R: https://github.com/ewallace/tidyqpcr/blob/master/R/plate_functions.R 

NICE: 
- create_blank_plate() nice pointer to the vignette info and great information on what to expect from outputs in terms of coercion, type etc
- like the user-friendly warnings in label_plate_rowcol() : https://github.com/ewallace/tidyqpcr/blob/master/R/plate_functions.R#L316

QUESTIONS/MAYBE-FIX: 
- not familiar enough with @importFrom to know if this changes how you'd refer to functions, but should for example 'as_factor()' be forcats::as_factor()? Or because of @importFrom in the roxygen2 code, does this not need to be specified in the code?  (https://github.com/ewallace/tidyqpcr/blob/master/R/plate_functions.R#L31 and Line 32.)  Also things like use of tibble()/as_tibble() in other functions, same idea. 

- within create_colkey_6_in_24() is `if(!missing(...){stuff}` the best way to do what looks like a test? Could assertthat() & co be better here? https://github.com/ewallace/tidyqpcr/blob/master/R/plate_functions.R#L96; same situation in create_rowkey_4_in_16(), create_rowkey_8_in_16_plain() functions also. 

- display_plate() function - are the internal ggplot parameters easy for users to edit (for example adjust theming for plots, by passing in extra parameters/arguments and their values, such as `legend.position` etc)?  I haven't tried this, but if this is something users CAN do, perhaps worth mentioning in the roxygen help text, or if it's NOT possible, worth saying to avoid folks trying? 

FIX: 
- create_blank_plate() function as_tibble() needs package::function format for consistency https://github.com/ewallace/tidyqpcr/blob/master/R/plate_functions.R#L33 
- create_blank_plate() doesn't return anything explicitly using return() function 

- create_colkey_4diln_2ctrl_in_24(), create_colkey_6diln_2ctrl_in_24  don't explicitly return()

- label_plate_rowcol() function: not sure which lines the comment - "# Note: should this if clause be a freestanding function? # coerce_column_to_factor(df, col, warn=TRUE)?" refers to? Make an issue ticket to clarify what needs to be done as a result.   https://github.com/ewallace/tidyqpcr/blob/master/R/plate_functions.R#L292

- display_plate() function: remove comment line with no comment: https://github.com/ewallace/tidyqpcr/blob/master/R/plate_functions.R#L349
- display_plate() function: fix/add example in roxygen code: https://github.com/ewallace/tidyqpcr/blob/master/R/plate_functions.R#L337 

# ----------- #

R SCRIPT: calculate_deltacq.R: https://github.com/ewallace/tidyqpcr/blob/master/R/calculate_deltacq.R 

NICE: 
- really full information for functions like calculate_deltadeltacq_bytargetid(), lots of detail about what to expect, it's clear why the variables are called that, and what to do in non-standard circumstances. Really approachable and helpful. 

QUESTIONS/MAYBE-FIX: 
- re: calculate_normvalue() @importFrom line: isn't '%>%' from magrittr package, not tidyr? https://github.com/ewallace/tidyqpcr/blob/master/R/calculate_deltacq.R#L23  

- for calculate_deltacq_bysampleid(): maybe explain what 'delta cq' means? or refer to where you've explained this in the package? I found it tricky to identify what 'cq' stands for?  The delta means a 'change in', doesn't it?  Is 'cq' related to 'quantification cycle'? Maybe users would know this stuff already, but for new users/inexperienced researchers it'd be handy to have a glossary/link to a resource with more details? 

 
FIX: 
- calculate_normvalue(): worth using assertthat() to test that the inputs are valid (ie of correct type, dimensions), if you're likely to be filtering with them, or puling bits out  
- calculate_normvalue() remove comment "note this is the same value for every row, a waste of space technically" - perhaps instead explain WHY assigning a summary if it's the same value for every row? Is this required downstream/in other functions? If not, worth removing? Justify why this method should remain if leaving it in.  https://github.com/ewallace/tidyqpcr/blob/master/R/calculate_deltacq.R#L38 

- calculate_deltacq_bysampleid() function doesn't explicitly return() cq_df 

- calculate_deltadeltacq_bytargetid() doesnt' explicitly return() anything either 

- in calculate_deltadeltacq_bytargetid(), dplyr::do() is SUPERCEDED, perhaps use alternatives suggested in dplyr docs (summarise(), nest_by() and across()) : https://dplyr.tidyverse.org/reference/do.html https://github.com/ewallace/tidyqpcr/blob/master/R/calculate_deltacq.R#L142 

# ----------- #

R SCRIPT: amp_melt_curve_functions.R: https://github.com/ewallace/tidyqpcr/blob/master/R/amp_melt_curve_functions.R

NICE: 
- nice, filled-out roxygen2 sections with lots of information on function parameters, etc. 
- functions nicely styled, easy to read, followed package::function format nicely, very informative.

QUESTIONS/MAYBE-FIX: 
- I didn't understand what's happening with last function getdRdTall(), presume getdRdTall() is deprecated, suggesting to use or instead using calculate_drdt_plate() instead? Is that correct? Not especially clear from reading the .R code though, perhaps could document this a little more? https://github.com/ewallace/tidyqpcr/blob/master/R/amp_melt_curve_functions.R#L125 

FIX: 

- BETA function debaseline(): question in comment about replacing "program_no == 2"; maybe worth creating issue ticket for this & tagging into code to tag it as priority, show progress or lack of it? Lines 11-14: https://github.com/ewallace/tidyqpcr/blob/master/R/amp_melt_curve_functions.R#L11
- debaseline(): comment saying "has not been tested robustly" - make issue ticket to test it? 
- debaseline() doesn't explicitly return anything?

- calculate_drdt_plate()  doesn't explicitly return anything? 
- calculate_drdt_plate() includes comment "# @ewallace: doesn't group by plate, only by well, so will fail strangely if used on data from multiple plates" - worth putting in the documentation of the function for users to be aware of?

**Comment by ewallace** [comment]
Great notes, very useful, thanks Flic!

Avoiding `return()` in functions was motivated by following the [tidyverse style guide](https://style.tidyverse.org/functions.html#return):
> Only use `return()` for early returns.

**Comment by DimmestP** [comment]
Apologies to the delay in response to all of this. I will now go about creating suitable issue tickets for the points raised.

Sam’s response to code review

**Main repo:**

Fix

- Check the suitability of the current colour scheme for accessibility
- Add the howfairis button to the README.md file
- Complete the Built-in functions to create plates with standard designs section in platesetup_vignette
- Add README.md file to extdata

Not-fix
- I do not agree that we use most of the tidyverse packages to justify its installation as a dependency. We may use 6 of the 8 core packages but the majority of the minor packages included in tidyverse (of which there are many) are not required.

**R SCRIPT: plate_functions.R**

Fix
- If you specify a function to import with @importFrom then you dont need to doubly specify with library::function. Perhaps we should be consistent with how in import functions?
- ggplot is build so that the last mention of a parameter overrides all previous assignments. Users can easily override defaults in the display_plate function using standard ggplot functions. We refer to that in roxygen text.
- remove comment on line 292
- add example for label_plate_rowcol
- create coerce_to_factor function

Not-fix 
- if(!missing(...){stuff} is not a test, it gives the user the option to add more experiment specific data to the colkey if they require.
- Unlike most other programming styles, tidyverse does not recommend explicit return calls.

**R SCRIPT: calculate_deltacq.R:**

Fix
- create a glossary of key terms (similar to LOO stan glossary https://github.com/stan-dev/loo/blob/master/R/loo-glossary.R)
- Update calls to “do” with superseded alternative
- remove comment about “waste of space” on line 38, this is just a consequence of long form tidy tables
- add assertthat to test filtered inputs

Not-fix
- %>% is originally from magrittr but since it is by far the most common pipe (and often the only thing used from the magrittr library) Rstudio decided to add it to tidyr

**R SCRIPT: amp_melt_curve_functions.R:**

Fix
- purpose of getdRdTall function
- add reference to multi-plate calculation in documentation
- test debaseline
- add issue about program_no
