### ISSUE TITLE
Add 'cowplot' as a dependency

### ISSUE THREAD

**Issue by vrob01** [ewallace/tidyqpcr#86]
Installing tidyqpcr on a vanilla installation of R 4.1, Win64 fails because the package "cowplot" cannot be found.

Solution: install cowplot (`install.packages(cowplot)`) solves the issue. Please add this to the installation guide.

**Comment by ewallace** [comment]
Thank you for the issue! 

We only use cowplot in the vignette, and list cowplot under "suggests" in the DESCRIPTION file. This is following [DESCRIPTION guidelines in R packages guide](https://r-pkgs.org/description.html#dependencies).

> Suggests: your package can use these packages, but doesn’t require them. You might use suggested packages for example datasets, to run tests, build vignettes, or maybe there’s only one function that needs the package.

So I'm not sure if this needs fixing. @DimmestP what do you think?

**Comment by vrob01** [comment]
In my instance, cowplot was required for a successful installation of tidyqpcr, so I don't think it falls under the criteria of "can use, but doesn't require". If there's a way around installing packages not strictly necessary for functionality, then I'm not aware of it and this issue should be closed ;)
However, if a dependency like cowplot is breaking installation and there's no way around it, it should not be listed as an optional dependency.

**Comment by DimmestP** [comment]
Hey! 

Thanks so much for commenting.

As Edward said, cowplot is never used in any of the tidyqpcr functions and so it is not a strict dependency. However, we encourage users to install the vignettes which teach you how to use tidyqpcr.

`devtools::install_github("ewallace/tidyqpcr",build_vignettes` = TRUE)`

These vignettes do use the cowplot package to make some of the figures. You can install tidyqpcr without making the vignettes  by removing the second argument and it will run perfectly fine.

`devtools::install_github("ewallace/tidyqpcr")`

I have added a line to the README file under [installing tidyqpcr](https://github.com/ewallace/tidyqpcr#installing-tidyqpcr) to make the distinction clear.
