### ISSUE TITLE
well_row as factor in helper functions

### ISSUE THREAD

**Issue by DimmestP** [ewallace/tidyqpcr#89]
Should `create_rowkey_4_in_16` and `create_rowkey_8_in_16_plain` rowkey helper functions automatically convert well_row to a factor? The equivalent colkey helper functions automatically covert well_col to a factor as this is required by `label_plate_rowcol`. Is there any reason not to do the same for rowkey to avoid the "coercing well_row to a factor" warning given by `label_plate_rowcol`? @ewallace

**Comment by ewallace** [comment]
Yes, good catch!
